exit task run if task exits with code other than 0

diff --git a/lib/task-runner b/lib/task-runner
--- a/lib/task-runner
+++ b/lib/task-runner
@@ -21,6 +21,10 @@ cat "$PROCFILE" | while read line; do
       echo "      running task ${TASK}"
       CMD=$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['${TASK}']")
       echo $CMD | bash -e | tee -a ${LOGDIR}/${TASK}-runner.log
+      if [ "$?" -ne 0 ];then
+        echo "${TASK} failed. aborting..."
+        exit $?
+      fi
       ;;
   esac
 done
